server:
  port: 8081

dtm:
  server:
    endpoint: '127.0.0.1:36789'

spring:
  datasource:
    url: jdbc:mysql://en.dtm.pub:3306/dtm_barrier?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
